---
- name: Provision and configure webservers
  hosts: webservers
  gather_facts: yes
  become: yes

  vars:
    html_content: |
      <!DOCTYPE html>
      <html lang="en">
      <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Terraform Test</title>
        <style>
          body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            background: linear-gradient(to right, #ff9966, #ff5e62);
          }
          h1 {
            font-size: 3em;
            color: white;
            text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.5);
          }
        </style>
      </head>
      <body>
        <h1>Welcome to {{ ansible_hostname }}!</h1>
      </body>
      </html>

  roles:
    - { role: geerlingguy.apache, httpd_packages: ['httpd'] }
    - { role: amazon.aws.ec2_instance_info }

  tasks:
    - name: Set timezone
      command: timedatectl set-timezone Africa/Lagos

    - name: Create index.html
      blockinfile:
        path: /var/www/html/index.html
        create: yes
        block: "{{ html_content }}"

    - name: Reload Apache
      service:
        name: httpd
        state: reloaded